// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agents.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAgent = `-- name: CreateAgent :one
INSERT INTO agents (workspace_id, name, description, instructions, model, runtime_id, enabled, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, workspace_id, name, description, instructions, model, runtime_id, enabled, created_by, created_at, updated_at
`

type CreateAgentParams struct {
	WorkspaceID  uuid.UUID  `json:"workspace_id"`
	Name         string     `json:"name"`
	Description  string     `json:"description"`
	Instructions string     `json:"instructions"`
	Model        string     `json:"model"`
	RuntimeID    uuid.UUID  `json:"runtime_id"`
	Enabled      bool       `json:"enabled"`
	CreatedBy    *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateAgent(ctx context.Context, arg CreateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, createAgent,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Model,
		arg.RuntimeID,
		arg.Enabled,
		arg.CreatedBy,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Model,
		&i.RuntimeID,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgent = `-- name: DeleteAgent :exec
DELETE FROM agents WHERE id = $1 AND workspace_id = $2
`

type DeleteAgentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteAgent(ctx context.Context, arg DeleteAgentParams) error {
	_, err := q.db.Exec(ctx, deleteAgent, arg.ID, arg.WorkspaceID)
	return err
}

const getAgent = `-- name: GetAgent :one
SELECT a.id, a.workspace_id, a.name, a.description, a.instructions, a.model, a.runtime_id, a.enabled, a.created_by, a.created_at, a.updated_at, ar.provider AS runtime_provider, ar.name AS runtime_name, ar.daemon_id AS runtime_daemon_id
FROM agents a
JOIN agent_runtimes ar ON ar.id = a.runtime_id
WHERE a.id = $1 AND a.workspace_id = $2
`

type GetAgentParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetAgentRow struct {
	ID              uuid.UUID  `json:"id"`
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	Name            string     `json:"name"`
	Description     string     `json:"description"`
	Instructions    string     `json:"instructions"`
	Model           string     `json:"model"`
	RuntimeID       uuid.UUID  `json:"runtime_id"`
	Enabled         bool       `json:"enabled"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	RuntimeProvider string     `json:"runtime_provider"`
	RuntimeName     string     `json:"runtime_name"`
	RuntimeDaemonID *uuid.UUID `json:"runtime_daemon_id"`
}

func (q *Queries) GetAgent(ctx context.Context, arg GetAgentParams) (GetAgentRow, error) {
	row := q.db.QueryRow(ctx, getAgent, arg.ID, arg.WorkspaceID)
	var i GetAgentRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Model,
		&i.RuntimeID,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RuntimeProvider,
		&i.RuntimeName,
		&i.RuntimeDaemonID,
	)
	return i, err
}

const listAgentNamesByWorkspace = `-- name: ListAgentNamesByWorkspace :many
SELECT name FROM agents WHERE workspace_id = $1 AND enabled = true ORDER BY name
`

func (q *Queries) ListAgentNamesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listAgentNamesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentsByWorkspace = `-- name: ListAgentsByWorkspace :many
SELECT a.id, a.workspace_id, a.name, a.description, a.instructions, a.model, a.runtime_id, a.enabled, a.created_by, a.created_at, a.updated_at, ar.provider AS runtime_provider, ar.name AS runtime_name, ar.daemon_id AS runtime_daemon_id
FROM agents a
JOIN agent_runtimes ar ON ar.id = a.runtime_id
WHERE a.workspace_id = $1
ORDER BY a.created_at ASC
`

type ListAgentsByWorkspaceRow struct {
	ID              uuid.UUID  `json:"id"`
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	Name            string     `json:"name"`
	Description     string     `json:"description"`
	Instructions    string     `json:"instructions"`
	Model           string     `json:"model"`
	RuntimeID       uuid.UUID  `json:"runtime_id"`
	Enabled         bool       `json:"enabled"`
	CreatedBy       *uuid.UUID `json:"created_by"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
	RuntimeProvider string     `json:"runtime_provider"`
	RuntimeName     string     `json:"runtime_name"`
	RuntimeDaemonID *uuid.UUID `json:"runtime_daemon_id"`
}

func (q *Queries) ListAgentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListAgentsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listAgentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentsByWorkspaceRow
	for rows.Next() {
		var i ListAgentsByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Instructions,
			&i.Model,
			&i.RuntimeID,
			&i.Enabled,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RuntimeProvider,
			&i.RuntimeName,
			&i.RuntimeDaemonID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgent = `-- name: UpdateAgent :one
UPDATE agents SET name = $3, description = $4, instructions = $5, model = $6, runtime_id = $7, enabled = $8, updated_at = now()
WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, name, description, instructions, model, runtime_id, enabled, created_by, created_at, updated_at
`

type UpdateAgentParams struct {
	ID           uuid.UUID `json:"id"`
	WorkspaceID  uuid.UUID `json:"workspace_id"`
	Name         string    `json:"name"`
	Description  string    `json:"description"`
	Instructions string    `json:"instructions"`
	Model        string    `json:"model"`
	RuntimeID    uuid.UUID `json:"runtime_id"`
	Enabled      bool      `json:"enabled"`
}

func (q *Queries) UpdateAgent(ctx context.Context, arg UpdateAgentParams) (Agent, error) {
	row := q.db.QueryRow(ctx, updateAgent,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Instructions,
		arg.Model,
		arg.RuntimeID,
		arg.Enabled,
	)
	var i Agent
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Instructions,
		&i.Model,
		&i.RuntimeID,
		&i.Enabled,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
