// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runtimes.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listAgentRuntimesByWorkspace = `-- name: ListAgentRuntimesByWorkspace :many
SELECT ar.id, ar.workspace_id, ar.daemon_id, ar.name, ar.runtime_mode, ar.provider, ar.device_info, ar.metadata, ar.created_at, ar.updated_at, d.name AS daemon_name, d.status AS daemon_status,
       d.last_seen_at AS daemon_last_seen_at
FROM agent_runtimes ar
LEFT JOIN daemons d ON d.id = ar.daemon_id
WHERE ar.workspace_id = $1
ORDER BY ar.created_at ASC
`

type ListAgentRuntimesByWorkspaceRow struct {
	ID               uuid.UUID  `json:"id"`
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	DaemonID         *uuid.UUID `json:"daemon_id"`
	Name             string     `json:"name"`
	RuntimeMode      string     `json:"runtime_mode"`
	Provider         string     `json:"provider"`
	DeviceInfo       string     `json:"device_info"`
	Metadata         []byte     `json:"metadata"`
	CreatedAt        time.Time  `json:"created_at"`
	UpdatedAt        time.Time  `json:"updated_at"`
	DaemonName       *string    `json:"daemon_name"`
	DaemonStatus     *string    `json:"daemon_status"`
	DaemonLastSeenAt *time.Time `json:"daemon_last_seen_at"`
}

// The daemon's last_seen_at comes along so the service can resolve liveness
// before the client sees it; see service.liveStatus.
func (q *Queries) ListAgentRuntimesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListAgentRuntimesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listAgentRuntimesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAgentRuntimesByWorkspaceRow
	for rows.Next() {
		var i ListAgentRuntimesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.DaemonID,
			&i.Name,
			&i.RuntimeMode,
			&i.Provider,
			&i.DeviceInfo,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DaemonName,
			&i.DaemonStatus,
			&i.DaemonLastSeenAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAgentRuntime = `-- name: UpsertAgentRuntime :one
INSERT INTO agent_runtimes (workspace_id, daemon_id, name, runtime_mode, provider)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (workspace_id, daemon_id, provider) DO UPDATE SET
    name = EXCLUDED.name, updated_at = now()
RETURNING id, workspace_id, daemon_id, name, runtime_mode, provider, device_info, metadata, created_at, updated_at
`

type UpsertAgentRuntimeParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	DaemonID    *uuid.UUID `json:"daemon_id"`
	Name        string     `json:"name"`
	RuntimeMode string     `json:"runtime_mode"`
	Provider    string     `json:"provider"`
}

func (q *Queries) UpsertAgentRuntime(ctx context.Context, arg UpsertAgentRuntimeParams) (AgentRuntime, error) {
	row := q.db.QueryRow(ctx, upsertAgentRuntime,
		arg.WorkspaceID,
		arg.DaemonID,
		arg.Name,
		arg.RuntimeMode,
		arg.Provider,
	)
	var i AgentRuntime
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.DaemonID,
		&i.Name,
		&i.RuntimeMode,
		&i.Provider,
		&i.DeviceInfo,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
