// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daemons.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const clearRuntimes = `-- name: ClearRuntimes :exec
DELETE FROM runtimes WHERE daemon_id = $1
`

// runtimes
func (q *Queries) ClearRuntimes(ctx context.Context, daemonID uuid.UUID) error {
	_, err := q.db.Exec(ctx, clearRuntimes, daemonID)
	return err
}

const confirmToken = `-- name: ConfirmToken :exec
UPDATE daemon_tokens SET status = 'active', user_id = $2, daemon_id = $3, confirmed_at = now()
WHERE id = $1 AND status = 'pending'
`

type ConfirmTokenParams struct {
	ID       uuid.UUID     `json:"id"`
	UserID   uuid.NullUUID `json:"user_id"`
	DaemonID uuid.NullUUID `json:"daemon_id"`
}

func (q *Queries) ConfirmToken(ctx context.Context, arg ConfirmTokenParams) error {
	_, err := q.db.Exec(ctx, confirmToken, arg.ID, arg.UserID, arg.DaemonID)
	return err
}

const consumePairingCode = `-- name: ConsumePairingCode :exec
UPDATE daemon_tokens SET pairing_code = NULL WHERE id = $1
`

func (q *Queries) ConsumePairingCode(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, consumePairingCode, id)
	return err
}

const createActiveToken = `-- name: CreateActiveToken :one
INSERT INTO daemon_tokens (user_id, token_hash, token_prefix, status)
VALUES ($1, $2, $3, 'active') RETURNING id, user_id, daemon_id, token_hash, token_prefix, pairing_code, machine_name, status, expires_at, issued_at, confirmed_at, last_used_at
`

type CreateActiveTokenParams struct {
	UserID      uuid.NullUUID `json:"user_id"`
	TokenHash   string        `json:"token_hash"`
	TokenPrefix string        `json:"token_prefix"`
}

func (q *Queries) CreateActiveToken(ctx context.Context, arg CreateActiveTokenParams) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, createActiveToken, arg.UserID, arg.TokenHash, arg.TokenPrefix)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.PairingCode,
		&i.MachineName,
		&i.Status,
		&i.ExpiresAt,
		&i.IssuedAt,
		&i.ConfirmedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const createDaemon = `-- name: CreateDaemon :one
INSERT INTO daemons (user_id, name) VALUES ($1, $2) RETURNING id, user_id, token_id, name, os, arch, daemon_version, status, last_seen_at, connected_at, registered_at
`

type CreateDaemonParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

// daemons
func (q *Queries) CreateDaemon(ctx context.Context, arg CreateDaemonParams) (Daemon, error) {
	row := q.db.QueryRow(ctx, createDaemon, arg.UserID, arg.Name)
	var i Daemon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.Name,
		&i.Os,
		&i.Arch,
		&i.DaemonVersion,
		&i.Status,
		&i.LastSeenAt,
		&i.ConnectedAt,
		&i.RegisteredAt,
	)
	return i, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO daemon_tokens (token_hash, token_prefix, pairing_code, machine_name, status, expires_at)
VALUES ($1, $2, $3, $4, 'pending', $5) RETURNING id, user_id, daemon_id, token_hash, token_prefix, pairing_code, machine_name, status, expires_at, issued_at, confirmed_at, last_used_at
`

type CreateTokenParams struct {
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	PairingCode *string            `json:"pairing_code"`
	MachineName *string            `json:"machine_name"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// daemon_tokens
func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.PairingCode,
		arg.MachineName,
		arg.ExpiresAt,
	)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.PairingCode,
		&i.MachineName,
		&i.Status,
		&i.ExpiresAt,
		&i.IssuedAt,
		&i.ConfirmedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const daemonOffline = `-- name: DaemonOffline :exec
UPDATE daemons SET status = 'offline' WHERE id = $1
`

func (q *Queries) DaemonOffline(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, daemonOffline, id)
	return err
}

const daemonOnline = `-- name: DaemonOnline :exec
UPDATE daemons SET last_seen_at = now(), status = 'online', connected_at = COALESCE(connected_at, now()) WHERE id = $1
`

func (q *Queries) DaemonOnline(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, daemonOnline, id)
	return err
}

const deleteDaemon = `-- name: DeleteDaemon :exec
DELETE FROM daemons WHERE id = $1
`

func (q *Queries) DeleteDaemon(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDaemon, id)
	return err
}

const expireToken = `-- name: ExpireToken :exec
UPDATE daemon_tokens SET status = 'expired' WHERE id = $1
`

func (q *Queries) ExpireToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, expireToken, id)
	return err
}

const findDaemonByID = `-- name: FindDaemonByID :one
SELECT id, user_id, token_id, name, os, arch, daemon_version, status, last_seen_at, connected_at, registered_at FROM daemons WHERE id = $1
`

func (q *Queries) FindDaemonByID(ctx context.Context, id uuid.UUID) (Daemon, error) {
	row := q.db.QueryRow(ctx, findDaemonByID, id)
	var i Daemon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.Name,
		&i.Os,
		&i.Arch,
		&i.DaemonVersion,
		&i.Status,
		&i.LastSeenAt,
		&i.ConnectedAt,
		&i.RegisteredAt,
	)
	return i, err
}

const findDaemonByUserAndName = `-- name: FindDaemonByUserAndName :one
SELECT id, user_id, token_id, name, os, arch, daemon_version, status, last_seen_at, connected_at, registered_at FROM daemons WHERE user_id = $1 AND name = $2
`

type FindDaemonByUserAndNameParams struct {
	UserID uuid.UUID `json:"user_id"`
	Name   string    `json:"name"`
}

func (q *Queries) FindDaemonByUserAndName(ctx context.Context, arg FindDaemonByUserAndNameParams) (Daemon, error) {
	row := q.db.QueryRow(ctx, findDaemonByUserAndName, arg.UserID, arg.Name)
	var i Daemon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenID,
		&i.Name,
		&i.Os,
		&i.Arch,
		&i.DaemonVersion,
		&i.Status,
		&i.LastSeenAt,
		&i.ConnectedAt,
		&i.RegisteredAt,
	)
	return i, err
}

const findTokenByHash = `-- name: FindTokenByHash :one
SELECT id, user_id, daemon_id, token_hash, token_prefix, pairing_code, machine_name, status, expires_at, issued_at, confirmed_at, last_used_at FROM daemon_tokens WHERE token_hash = $1
`

func (q *Queries) FindTokenByHash(ctx context.Context, tokenHash string) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, findTokenByHash, tokenHash)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.PairingCode,
		&i.MachineName,
		&i.Status,
		&i.ExpiresAt,
		&i.IssuedAt,
		&i.ConfirmedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const findTokenByPairingCode = `-- name: FindTokenByPairingCode :one
SELECT id, user_id, daemon_id, token_hash, token_prefix, pairing_code, machine_name, status, expires_at, issued_at, confirmed_at, last_used_at FROM daemon_tokens WHERE pairing_code = $1
`

func (q *Queries) FindTokenByPairingCode(ctx context.Context, pairingCode *string) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, findTokenByPairingCode, pairingCode)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.PairingCode,
		&i.MachineName,
		&i.Status,
		&i.ExpiresAt,
		&i.IssuedAt,
		&i.ConfirmedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const insertRuntime = `-- name: InsertRuntime :exec
INSERT INTO runtimes (daemon_id, kind, name, executable_path, version, status, diagnostics, max_concurrency)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (daemon_id, kind, name) DO UPDATE SET
    executable_path = EXCLUDED.executable_path, version = EXCLUDED.version,
    status = EXCLUDED.status, diagnostics = EXCLUDED.diagnostics,
    checked_at = now()
`

type InsertRuntimeParams struct {
	DaemonID       uuid.UUID `json:"daemon_id"`
	Kind           string    `json:"kind"`
	Name           string    `json:"name"`
	ExecutablePath *string   `json:"executable_path"`
	Version        *string   `json:"version"`
	Status         string    `json:"status"`
	Diagnostics    *string   `json:"diagnostics"`
	MaxConcurrency int32     `json:"max_concurrency"`
}

func (q *Queries) InsertRuntime(ctx context.Context, arg InsertRuntimeParams) error {
	_, err := q.db.Exec(ctx, insertRuntime,
		arg.DaemonID,
		arg.Kind,
		arg.Name,
		arg.ExecutablePath,
		arg.Version,
		arg.Status,
		arg.Diagnostics,
		arg.MaxConcurrency,
	)
	return err
}

const listDaemonsByUser = `-- name: ListDaemonsByUser :many
SELECT d.id, d.user_id, d.token_id, d.name, d.os, d.arch, d.daemon_version, d.status, d.last_seen_at, d.connected_at, d.registered_at, r.id AS r_id, r.kind AS r_kind, r.name AS r_name,
       r.executable_path AS r_executable_path, r.version AS r_version,
       r.status AS r_status, r.diagnostics AS r_diagnostics,
       r.max_concurrency AS r_max_concurrency
FROM daemons d
LEFT JOIN runtimes r ON r.daemon_id = d.id
WHERE d.user_id = $1
ORDER BY d.registered_at DESC, r.kind, r.name
`

type ListDaemonsByUserRow struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	TokenID         uuid.NullUUID      `json:"token_id"`
	Name            string             `json:"name"`
	Os              string             `json:"os"`
	Arch            string             `json:"arch"`
	DaemonVersion   string             `json:"daemon_version"`
	Status          string             `json:"status"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	ConnectedAt     pgtype.Timestamptz `json:"connected_at"`
	RegisteredAt    pgtype.Timestamptz `json:"registered_at"`
	RID             uuid.NullUUID      `json:"r_id"`
	RKind           *string            `json:"r_kind"`
	RName           *string            `json:"r_name"`
	RExecutablePath *string            `json:"r_executable_path"`
	RVersion        *string            `json:"r_version"`
	RStatus         *string            `json:"r_status"`
	RDiagnostics    *string            `json:"r_diagnostics"`
	RMaxConcurrency *int32             `json:"r_max_concurrency"`
}

func (q *Queries) ListDaemonsByUser(ctx context.Context, userID uuid.UUID) ([]ListDaemonsByUserRow, error) {
	rows, err := q.db.Query(ctx, listDaemonsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDaemonsByUserRow
	for rows.Next() {
		var i ListDaemonsByUserRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TokenID,
			&i.Name,
			&i.Os,
			&i.Arch,
			&i.DaemonVersion,
			&i.Status,
			&i.LastSeenAt,
			&i.ConnectedAt,
			&i.RegisteredAt,
			&i.RID,
			&i.RKind,
			&i.RName,
			&i.RExecutablePath,
			&i.RVersion,
			&i.RStatus,
			&i.RDiagnostics,
			&i.RMaxConcurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTokenHash = `-- name: SetTokenHash :exec
UPDATE daemon_tokens SET token_hash = $2, token_prefix = $3 WHERE id = $1
`

type SetTokenHashParams struct {
	ID          uuid.UUID `json:"id"`
	TokenHash   string    `json:"token_hash"`
	TokenPrefix string    `json:"token_prefix"`
}

func (q *Queries) SetTokenHash(ctx context.Context, arg SetTokenHashParams) error {
	_, err := q.db.Exec(ctx, setTokenHash, arg.ID, arg.TokenHash, arg.TokenPrefix)
	return err
}

const touchToken = `-- name: TouchToken :exec
UPDATE daemon_tokens SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchToken, id)
	return err
}

const updateDaemonInfo = `-- name: UpdateDaemonInfo :exec
UPDATE daemons SET name = $2, os = $3, arch = $4, daemon_version = $5 WHERE id = $1
`

type UpdateDaemonInfoParams struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	Os            string    `json:"os"`
	Arch          string    `json:"arch"`
	DaemonVersion string    `json:"daemon_version"`
}

func (q *Queries) UpdateDaemonInfo(ctx context.Context, arg UpdateDaemonInfoParams) error {
	_, err := q.db.Exec(ctx, updateDaemonInfo,
		arg.ID,
		arg.Name,
		arg.Os,
		arg.Arch,
		arg.DaemonVersion,
	)
	return err
}
