// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: github.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createInstallation = `-- name: CreateInstallation :one
INSERT INTO github_installations
    (user_id, installation_id, account_login, account_type, repository_selection)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (installation_id)
DO UPDATE SET
    user_id = COALESCE(EXCLUDED.user_id, github_installations.user_id),
    account_login = EXCLUDED.account_login,
    account_type = EXCLUDED.account_type,
    repository_selection = EXCLUDED.repository_selection,
    status = CASE WHEN github_installations.status = 'revoked' THEN 'active' ELSE github_installations.status END,
    updated_at = now()
RETURNING id, user_id, installation_id, account_login, account_type, repository_selection, status, created_at, updated_at
`

type CreateInstallationParams struct {
	UserID              *uuid.UUID `json:"user_id"`
	InstallationID      int64      `json:"installation_id"`
	AccountLogin        string     `json:"account_login"`
	AccountType         string     `json:"account_type"`
	RepositorySelection string     `json:"repository_selection"`
}

func (q *Queries) CreateInstallation(ctx context.Context, arg CreateInstallationParams) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, createInstallation,
		arg.UserID,
		arg.InstallationID,
		arg.AccountLogin,
		arg.AccountType,
		arg.RepositorySelection,
	)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createWebhookEvent = `-- name: CreateWebhookEvent :exec
INSERT INTO webhook_events (github_delivery_id, event_type, action, payload)
VALUES ($1, $2, $3, $4)
ON CONFLICT (github_delivery_id) DO NOTHING
`

type CreateWebhookEventParams struct {
	GithubDeliveryID *string `json:"github_delivery_id"`
	EventType        string  `json:"event_type"`
	Action           *string `json:"action"`
	Payload          []byte  `json:"payload"`
}

func (q *Queries) CreateWebhookEvent(ctx context.Context, arg CreateWebhookEventParams) error {
	_, err := q.db.Exec(ctx, createWebhookEvent,
		arg.GithubDeliveryID,
		arg.EventType,
		arg.Action,
		arg.Payload,
	)
	return err
}

const deleteReposNotInList = `-- name: DeleteReposNotInList :exec
DELETE FROM github_repos
WHERE installation_id = $1 AND github_repo_id != ALL($2::bigint[])
`

type DeleteReposNotInListParams struct {
	InstallationID uuid.UUID `json:"installation_id"`
	Column2        []int64   `json:"column_2"`
}

func (q *Queries) DeleteReposNotInList(ctx context.Context, arg DeleteReposNotInListParams) error {
	_, err := q.db.Exec(ctx, deleteReposNotInList, arg.InstallationID, arg.Column2)
	return err
}

const getInstallation = `-- name: GetInstallation :one
SELECT id, user_id, installation_id, account_login, account_type, repository_selection, status, created_at, updated_at FROM github_installations WHERE installation_id = $1
`

func (q *Queries) GetInstallation(ctx context.Context, installationID int64) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallation, installationID)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstallationByDBID = `-- name: GetInstallationByDBID :one
SELECT id, user_id, installation_id, account_login, account_type, repository_selection, status, created_at, updated_at FROM github_installations WHERE id = $1
`

func (q *Queries) GetInstallationByDBID(ctx context.Context, id uuid.UUID) (GithubInstallation, error) {
	row := q.db.QueryRow(ctx, getInstallationByDBID, id)
	var i GithubInstallation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.AccountLogin,
		&i.AccountType,
		&i.RepositorySelection,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstallationsByUser = `-- name: ListInstallationsByUser :many
SELECT id, user_id, installation_id, account_login, account_type, repository_selection, status, created_at, updated_at FROM github_installations WHERE (user_id = $1 OR user_id IS NULL) AND status != 'revoked' ORDER BY created_at DESC
`

func (q *Queries) ListInstallationsByUser(ctx context.Context, userID *uuid.UUID) ([]GithubInstallation, error) {
	rows, err := q.db.Query(ctx, listInstallationsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubInstallation
	for rows.Next() {
		var i GithubInstallation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.AccountLogin,
			&i.AccountType,
			&i.RepositorySelection,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReposByInstallation = `-- name: ListReposByInstallation :many
SELECT id, installation_id, github_repo_id, owner, name, full_name, private FROM github_repos WHERE installation_id = $1 ORDER BY full_name
`

func (q *Queries) ListReposByInstallation(ctx context.Context, installationID uuid.UUID) ([]GithubRepo, error) {
	rows, err := q.db.Query(ctx, listReposByInstallation, installationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GithubRepo
	for rows.Next() {
		var i GithubRepo
		if err := rows.Scan(
			&i.ID,
			&i.InstallationID,
			&i.GithubRepoID,
			&i.Owner,
			&i.Name,
			&i.FullName,
			&i.Private,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInstallationStatus = `-- name: UpdateInstallationStatus :exec
UPDATE github_installations SET status = $2, updated_at = now() WHERE installation_id = $1
`

type UpdateInstallationStatusParams struct {
	InstallationID int64  `json:"installation_id"`
	Status         string `json:"status"`
}

func (q *Queries) UpdateInstallationStatus(ctx context.Context, arg UpdateInstallationStatusParams) error {
	_, err := q.db.Exec(ctx, updateInstallationStatus, arg.InstallationID, arg.Status)
	return err
}

const upsertRepo = `-- name: UpsertRepo :exec
INSERT INTO github_repos (installation_id, github_repo_id, owner, name, full_name, private)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (installation_id, github_repo_id)
DO UPDATE SET owner = EXCLUDED.owner, name = EXCLUDED.name, full_name = EXCLUDED.full_name, private = EXCLUDED.private
`

type UpsertRepoParams struct {
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   int64     `json:"github_repo_id"`
	Owner          string    `json:"owner"`
	Name           string    `json:"name"`
	FullName       string    `json:"full_name"`
	Private        bool      `json:"private"`
}

func (q *Queries) UpsertRepo(ctx context.Context, arg UpsertRepoParams) error {
	_, err := q.db.Exec(ctx, upsertRepo,
		arg.InstallationID,
		arg.GithubRepoID,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.Private,
	)
	return err
}
