// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_agents.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const addIssueAgent = `-- name: AddIssueAgent :exec
INSERT INTO issue_agents (issue_id, agent_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddIssueAgentParams struct {
	IssueID uuid.UUID `json:"issue_id"`
	AgentID uuid.UUID `json:"agent_id"`
}

// The pair is the primary key, so a repeat is a no-op: mention-triggered
// assignment and the picker can both be called twice safely.
func (q *Queries) AddIssueAgent(ctx context.Context, arg AddIssueAgentParams) error {
	_, err := q.db.Exec(ctx, addIssueAgent, arg.IssueID, arg.AgentID)
	return err
}

const deleteIssueAgents = `-- name: DeleteIssueAgents :exec
DELETE FROM issue_agents WHERE issue_id = $1
`

func (q *Queries) DeleteIssueAgents(ctx context.Context, issueID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteIssueAgents, issueID)
	return err
}

const listIssueAgents = `-- name: ListIssueAgents :many

SELECT a.id, a.name, COALESCE(a.avatar_url, '') AS avatar_url,
       CASE WHEN bool_or(t.status IN ('dispatched','running')) THEN 'running'
            WHEN bool_or(t.status = 'queued')             THEN 'queued'
            ELSE 'idle' END::text AS state
FROM issue_agents ia
JOIN agents a ON a.id = ia.agent_id
LEFT JOIN tasks t ON t.issue_id = ia.issue_id AND t.agent_id = ia.agent_id
WHERE ia.issue_id = $1
GROUP BY a.id, a.name, a.avatar_url, a.created_at
ORDER BY a.created_at
`

type ListIssueAgentsRow struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	AvatarUrl string    `json:"avatar_url"`
	State     string    `json:"state"`
}

// Who works on an issue, with what each agent is doing on it right now.
//
// The state is derived per (issue, agent) rather than read off the agent: an
// agent's own "current task" is its newest one anywhere, while this answers
// "what is it doing *here*". A task that is dispatched or running wins over one
// still queued, so a fresh queued task never hides work already in flight.
func (q *Queries) ListIssueAgents(ctx context.Context, issueID uuid.UUID) ([]ListIssueAgentsRow, error) {
	rows, err := q.db.Query(ctx, listIssueAgents, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueAgentsRow
	for rows.Next() {
		var i ListIssueAgentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AvatarUrl,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueAgentsByWorkspace = `-- name: ListIssueAgentsByWorkspace :many
SELECT ia.issue_id, a.id, a.name, COALESCE(a.avatar_url, '') AS avatar_url,
       CASE WHEN bool_or(t.status IN ('dispatched','running')) THEN 'running'
            WHEN bool_or(t.status = 'queued')             THEN 'queued'
            ELSE 'idle' END::text AS state
FROM issue_agents ia
JOIN issues i ON i.id = ia.issue_id
JOIN agents a ON a.id = ia.agent_id
LEFT JOIN tasks t ON t.issue_id = ia.issue_id AND t.agent_id = ia.agent_id
WHERE i.workspace_id = $1
GROUP BY ia.issue_id, a.id, a.name, a.avatar_url, a.created_at
ORDER BY ia.issue_id, a.created_at
`

type ListIssueAgentsByWorkspaceRow struct {
	IssueID   uuid.UUID `json:"issue_id"`
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	AvatarUrl string    `json:"avatar_url"`
	State     string    `json:"state"`
}

// The board's version: every assignment in the workspace in one read, so the
// service can group by issue_id instead of running a query per card.
func (q *Queries) ListIssueAgentsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListIssueAgentsByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listIssueAgentsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueAgentsByWorkspaceRow
	for rows.Next() {
		var i ListIssueAgentsByWorkspaceRow
		if err := rows.Scan(
			&i.IssueID,
			&i.ID,
			&i.Name,
			&i.AvatarUrl,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
