// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO issue_comments (issue_id, author_type, author_id, author_name, type, content)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, issue_id, author_type, author_id, author_name, type, content, created_at
`

type CreateCommentParams struct {
	IssueID    uuid.UUID  `json:"issue_id"`
	AuthorType string     `json:"author_type"`
	AuthorID   *uuid.UUID `json:"author_id"`
	AuthorName string     `json:"author_name"`
	Type       string     `json:"type"`
	Content    string     `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (IssueComment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.IssueID,
		arg.AuthorType,
		arg.AuthorID,
		arg.AuthorName,
		arg.Type,
		arg.Content,
	)
	var i IssueComment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorType,
		&i.AuthorID,
		&i.AuthorName,
		&i.Type,
		&i.Content,
		&i.CreatedAt,
	)
	return i, err
}

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues (workspace_id, number, title, description, status, creator_user_id, assignee_user_id, source_upstream_issue)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING id, workspace_id, number, title, description, status, creator_user_id, assignee_user_id, source_upstream_issue, created_at, updated_at
`

type CreateIssueParams struct {
	WorkspaceID         uuid.UUID  `json:"workspace_id"`
	Number              int32      `json:"number"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Status              string     `json:"status"`
	CreatorUserID       *uuid.UUID `json:"creator_user_id"`
	AssigneeUserID      *uuid.UUID `json:"assignee_user_id"`
	SourceUpstreamIssue *string    `json:"source_upstream_issue"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.WorkspaceID,
		arg.Number,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.CreatorUserID,
		arg.AssigneeUserID,
		arg.SourceUpstreamIssue,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatorUserID,
		&i.AssigneeUserID,
		&i.SourceUpstreamIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIssue = `-- name: GetIssue :one
SELECT i.id, i.workspace_id, i.number, i.title, i.description, i.status, i.creator_user_id, i.assignee_user_id, i.source_upstream_issue, i.created_at, i.updated_at, w.issue_prefix AS issue_prefix, COALESCE(u.login, '') AS creator_name,
       au.id AS assignee_id, COALESCE(au.login, '') AS assignee_login,
       COALESCE(au.avatar_url, '') AS assignee_avatar_url,
       (SELECT count(*) FROM issue_comments c WHERE c.issue_id = i.id) AS comments_count
FROM issues i
JOIN workspaces w ON w.id = i.workspace_id
LEFT JOIN users u ON u.id = i.creator_user_id
LEFT JOIN users au ON au.id = i.assignee_user_id
WHERE i.id = $1 AND i.workspace_id = $2
`

type GetIssueParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

type GetIssueRow struct {
	ID                  uuid.UUID  `json:"id"`
	WorkspaceID         uuid.UUID  `json:"workspace_id"`
	Number              int32      `json:"number"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Status              string     `json:"status"`
	CreatorUserID       *uuid.UUID `json:"creator_user_id"`
	AssigneeUserID      *uuid.UUID `json:"assignee_user_id"`
	SourceUpstreamIssue *string    `json:"source_upstream_issue"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	IssuePrefix         string     `json:"issue_prefix"`
	CreatorName         string     `json:"creator_name"`
	AssigneeID          *uuid.UUID `json:"assignee_id"`
	AssigneeLogin       string     `json:"assignee_login"`
	AssigneeAvatarUrl   string     `json:"assignee_avatar_url"`
	CommentsCount       int64      `json:"comments_count"`
}

func (q *Queries) GetIssue(ctx context.Context, arg GetIssueParams) (GetIssueRow, error) {
	row := q.db.QueryRow(ctx, getIssue, arg.ID, arg.WorkspaceID)
	var i GetIssueRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatorUserID,
		&i.AssigneeUserID,
		&i.SourceUpstreamIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuePrefix,
		&i.CreatorName,
		&i.AssigneeID,
		&i.AssigneeLogin,
		&i.AssigneeAvatarUrl,
		&i.CommentsCount,
	)
	return i, err
}

const getIssueByNumber = `-- name: GetIssueByNumber :one
SELECT i.id, i.workspace_id, i.number, i.title, i.description, i.status, i.creator_user_id, i.assignee_user_id, i.source_upstream_issue, i.created_at, i.updated_at, w.issue_prefix AS issue_prefix, COALESCE(u.login, '') AS creator_name,
       au.id AS assignee_id, COALESCE(au.login, '') AS assignee_login,
       COALESCE(au.avatar_url, '') AS assignee_avatar_url,
       (SELECT count(*) FROM issue_comments c WHERE c.issue_id = i.id) AS comments_count
FROM issues i
JOIN workspaces w ON w.id = i.workspace_id
LEFT JOIN users u ON u.id = i.creator_user_id
LEFT JOIN users au ON au.id = i.assignee_user_id
WHERE i.workspace_id = $1 AND i.number = $2
`

type GetIssueByNumberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Number      int32     `json:"number"`
}

type GetIssueByNumberRow struct {
	ID                  uuid.UUID  `json:"id"`
	WorkspaceID         uuid.UUID  `json:"workspace_id"`
	Number              int32      `json:"number"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Status              string     `json:"status"`
	CreatorUserID       *uuid.UUID `json:"creator_user_id"`
	AssigneeUserID      *uuid.UUID `json:"assignee_user_id"`
	SourceUpstreamIssue *string    `json:"source_upstream_issue"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	IssuePrefix         string     `json:"issue_prefix"`
	CreatorName         string     `json:"creator_name"`
	AssigneeID          *uuid.UUID `json:"assignee_id"`
	AssigneeLogin       string     `json:"assignee_login"`
	AssigneeAvatarUrl   string     `json:"assignee_avatar_url"`
	CommentsCount       int64      `json:"comments_count"`
}

func (q *Queries) GetIssueByNumber(ctx context.Context, arg GetIssueByNumberParams) (GetIssueByNumberRow, error) {
	row := q.db.QueryRow(ctx, getIssueByNumber, arg.WorkspaceID, arg.Number)
	var i GetIssueByNumberRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatorUserID,
		&i.AssigneeUserID,
		&i.SourceUpstreamIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuePrefix,
		&i.CreatorName,
		&i.AssigneeID,
		&i.AssigneeLogin,
		&i.AssigneeAvatarUrl,
		&i.CommentsCount,
	)
	return i, err
}

const getWorkspaceNumbering = `-- name: GetWorkspaceNumbering :one
SELECT issue_prefix FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspaceNumbering(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getWorkspaceNumbering, id)
	var issue_prefix string
	err := row.Scan(&issue_prefix)
	return issue_prefix, err
}

const incrementWorkspaceIssueCounter = `-- name: IncrementWorkspaceIssueCounter :one
UPDATE workspaces SET issue_counter = issue_counter + 1 WHERE id = $1 RETURNING issue_counter
`

func (q *Queries) IncrementWorkspaceIssueCounter(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, incrementWorkspaceIssueCounter, id)
	var issue_counter int32
	err := row.Scan(&issue_counter)
	return issue_counter, err
}

const listCommentsByIssue = `-- name: ListCommentsByIssue :many
SELECT id, issue_id, author_type, author_id, author_name, type, content, created_at FROM issue_comments WHERE issue_id = $1 ORDER BY created_at ASC
`

func (q *Queries) ListCommentsByIssue(ctx context.Context, issueID uuid.UUID) ([]IssueComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IssueComment
	for rows.Next() {
		var i IssueComment
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorType,
			&i.AuthorID,
			&i.AuthorName,
			&i.Type,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssuesByWorkspace = `-- name: ListIssuesByWorkspace :many
SELECT i.id, i.workspace_id, i.number, i.title, i.description, i.status, i.creator_user_id, i.assignee_user_id, i.source_upstream_issue, i.created_at, i.updated_at, w.issue_prefix AS issue_prefix, COALESCE(u.login, '') AS creator_name,
       au.id AS assignee_id, COALESCE(au.login, '') AS assignee_login,
       COALESCE(au.avatar_url, '') AS assignee_avatar_url,
       (SELECT count(*) FROM issue_comments c WHERE c.issue_id = i.id) AS comments_count,
       COALESCE((SELECT pr.number FROM pull_requests pr
                 WHERE pr.issue_id = i.id AND pr.state = 'open' AND pr.close_intent
                   AND pr.suppressed_at IS NULL
                 ORDER BY pr.created_at DESC LIMIT 1), 0)::int AS active_pr_number
FROM issues i
JOIN workspaces w ON w.id = i.workspace_id
LEFT JOIN users u ON u.id = i.creator_user_id
LEFT JOIN users au ON au.id = i.assignee_user_id
WHERE i.workspace_id = $1
ORDER BY i.status, i.created_at DESC
`

type ListIssuesByWorkspaceRow struct {
	ID                  uuid.UUID  `json:"id"`
	WorkspaceID         uuid.UUID  `json:"workspace_id"`
	Number              int32      `json:"number"`
	Title               string     `json:"title"`
	Description         string     `json:"description"`
	Status              string     `json:"status"`
	CreatorUserID       *uuid.UUID `json:"creator_user_id"`
	AssigneeUserID      *uuid.UUID `json:"assignee_user_id"`
	SourceUpstreamIssue *string    `json:"source_upstream_issue"`
	CreatedAt           time.Time  `json:"created_at"`
	UpdatedAt           time.Time  `json:"updated_at"`
	IssuePrefix         string     `json:"issue_prefix"`
	CreatorName         string     `json:"creator_name"`
	AssigneeID          *uuid.UUID `json:"assignee_id"`
	AssigneeLogin       string     `json:"assignee_login"`
	AssigneeAvatarUrl   string     `json:"assignee_avatar_url"`
	CommentsCount       int64      `json:"comments_count"`
	ActivePrNumber      int32      `json:"active_pr_number"`
}

func (q *Queries) ListIssuesByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]ListIssuesByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listIssuesByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssuesByWorkspaceRow
	for rows.Next() {
		var i ListIssuesByWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Number,
			&i.Title,
			&i.Description,
			&i.Status,
			&i.CreatorUserID,
			&i.AssigneeUserID,
			&i.SourceUpstreamIssue,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssuePrefix,
			&i.CreatorName,
			&i.AssigneeID,
			&i.AssigneeLogin,
			&i.AssigneeAvatarUrl,
			&i.CommentsCount,
			&i.ActivePrNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateIssueAssignee = `-- name: UpdateIssueAssignee :one
UPDATE issues SET assignee_user_id = $3::uuid, updated_at = now()
WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, number, title, description, status, creator_user_id, assignee_user_id, source_upstream_issue, created_at, updated_at
`

type UpdateIssueAssigneeParams struct {
	ID             uuid.UUID  `json:"id"`
	WorkspaceID    uuid.UUID  `json:"workspace_id"`
	AssigneeUserID *uuid.UUID `json:"assignee_user_id"`
}

// The one person accountable for the issue; NULL clears it. A separate query
// from the other field updates so a status-only edit can never touch it.
func (q *Queries) UpdateIssueAssignee(ctx context.Context, arg UpdateIssueAssigneeParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueAssignee, arg.ID, arg.WorkspaceID, arg.AssigneeUserID)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatorUserID,
		&i.AssigneeUserID,
		&i.SourceUpstreamIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE issues SET status = $3, updated_at = now() WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, number, title, description, status, creator_user_id, assignee_user_id, source_upstream_issue, created_at, updated_at
`

type UpdateIssueStatusParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Status      string    `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueStatus, arg.ID, arg.WorkspaceID, arg.Status)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatorUserID,
		&i.AssigneeUserID,
		&i.SourceUpstreamIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIssueTitleDescription = `-- name: UpdateIssueTitleDescription :one
UPDATE issues SET title = $3, description = $4, updated_at = now() WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, number, title, description, status, creator_user_id, assignee_user_id, source_upstream_issue, created_at, updated_at
`

type UpdateIssueTitleDescriptionParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
}

func (q *Queries) UpdateIssueTitleDescription(ctx context.Context, arg UpdateIssueTitleDescriptionParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueTitleDescription,
		arg.ID,
		arg.WorkspaceID,
		arg.Title,
		arg.Description,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Number,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.CreatorUserID,
		&i.AssigneeUserID,
		&i.SourceUpstreamIssue,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
