// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"

	"github.com/google/uuid"
)

type Daemon struct {
	ID            uuid.UUID  `json:"id"`
	UserID        uuid.UUID  `json:"user_id"`
	TokenID       *uuid.UUID `json:"token_id"`
	Name          string     `json:"name"`
	Os            string     `json:"os"`
	Arch          string     `json:"arch"`
	DaemonVersion string     `json:"daemon_version"`
	Status        string     `json:"status"`
	LastSeenAt    *time.Time `json:"last_seen_at"`
	ConnectedAt   *time.Time `json:"connected_at"`
	RegisteredAt  time.Time  `json:"registered_at"`
}

type DaemonToken struct {
	ID          uuid.UUID  `json:"id"`
	UserID      *uuid.UUID `json:"user_id"`
	DaemonID    *uuid.UUID `json:"daemon_id"`
	TokenHash   string     `json:"token_hash"`
	TokenPrefix string     `json:"token_prefix"`
	PairingCode *string    `json:"pairing_code"`
	MachineName *string    `json:"machine_name"`
	Status      string     `json:"status"`
	ExpiresAt   *time.Time `json:"expires_at"`
	IssuedAt    time.Time  `json:"issued_at"`
	ConfirmedAt *time.Time `json:"confirmed_at"`
	LastUsedAt  *time.Time `json:"last_used_at"`
}

type GithubInstallation struct {
	ID                  uuid.UUID `json:"id"`
	UserID              uuid.UUID `json:"user_id"`
	InstallationID      int64     `json:"installation_id"`
	AccountLogin        string    `json:"account_login"`
	AccountType         string    `json:"account_type"`
	RepositorySelection string    `json:"repository_selection"`
	Status              string    `json:"status"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type GithubRepo struct {
	ID             uuid.UUID `json:"id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   int64     `json:"github_repo_id"`
	Owner          string    `json:"owner"`
	Name           string    `json:"name"`
	FullName       string    `json:"full_name"`
	Private        bool      `json:"private"`
}

type Runtime struct {
	ID             uuid.UUID `json:"id"`
	DaemonID       uuid.UUID `json:"daemon_id"`
	Kind           string    `json:"kind"`
	Name           string    `json:"name"`
	ExecutablePath string    `json:"executable_path"`
	Version        string    `json:"version"`
	Status         string    `json:"status"`
	CheckedAt      time.Time `json:"checked_at"`
	Diagnostics    *string   `json:"diagnostics"`
	MaxConcurrency int32     `json:"max_concurrency"`
}

type User struct {
	ID        uuid.UUID `json:"id"`
	Login     string    `json:"login"`
	AvatarUrl *string   `json:"avatar_url"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type UserIdentity struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	ProviderLogin  string    `json:"provider_login"`
	Email          *string   `json:"email"`
	AccessToken    *string   `json:"access_token"`
	RefreshToken   *string   `json:"refresh_token"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}

type WebhookEvent struct {
	ID               uuid.UUID `json:"id"`
	GithubDeliveryID *string   `json:"github_delivery_id"`
	EventType        string    `json:"event_type"`
	Action           *string   `json:"action"`
	Payload          []byte    `json:"payload"`
	Processed        bool      `json:"processed"`
	CreatedAt        time.Time `json:"created_at"`
}

type Workspace struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
}
