// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Daemon struct {
	ID            uuid.UUID          `json:"id"`
	UserID        uuid.UUID          `json:"user_id"`
	TokenID       uuid.NullUUID      `json:"token_id"`
	Name          string             `json:"name"`
	Os            string             `json:"os"`
	Arch          string             `json:"arch"`
	DaemonVersion string             `json:"daemon_version"`
	Status        string             `json:"status"`
	LastSeenAt    pgtype.Timestamptz `json:"last_seen_at"`
	ConnectedAt   pgtype.Timestamptz `json:"connected_at"`
	RegisteredAt  pgtype.Timestamptz `json:"registered_at"`
}

type DaemonToken struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.NullUUID      `json:"user_id"`
	DaemonID    uuid.NullUUID      `json:"daemon_id"`
	TokenHash   string             `json:"token_hash"`
	TokenPrefix string             `json:"token_prefix"`
	PairingCode *string            `json:"pairing_code"`
	MachineName *string            `json:"machine_name"`
	Status      string             `json:"status"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	ConfirmedAt pgtype.Timestamptz `json:"confirmed_at"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
}

type Runtime struct {
	ID             uuid.UUID          `json:"id"`
	DaemonID       uuid.UUID          `json:"daemon_id"`
	Kind           string             `json:"kind"`
	Name           string             `json:"name"`
	ExecutablePath *string            `json:"executable_path"`
	Version        *string            `json:"version"`
	Status         string             `json:"status"`
	CheckedAt      pgtype.Timestamptz `json:"checked_at"`
	Diagnostics    *string            `json:"diagnostics"`
	MaxConcurrency int32              `json:"max_concurrency"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Login     string             `json:"login"`
	AvatarUrl *string            `json:"avatar_url"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type UserIdentity struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	ProviderLogin  string             `json:"provider_login"`
	Email          *string            `json:"email"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
