// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pull_requests.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countOpenClosingPullRequests = `-- name: CountOpenClosingPullRequests :one
SELECT
    COUNT(*) FILTER (WHERE state = 'open' AND suppressed_at IS NULL)::bigint AS open_count,
    COUNT(*) FILTER (WHERE state = 'merged' AND close_intent AND suppressed_at IS NULL)::bigint AS merged_closing_count
FROM pull_requests
WHERE issue_id = $1
`

type CountOpenClosingPullRequestsRow struct {
	OpenCount          int64 `json:"open_count"`
	MergedClosingCount int64 `json:"merged_closing_count"`
}

// Feeds the aggregate that decides whether the issue is finished: the issue is
// done when nothing is in flight and something merged with closing intent.
func (q *Queries) CountOpenClosingPullRequests(ctx context.Context, issueID uuid.UUID) (CountOpenClosingPullRequestsRow, error) {
	row := q.db.QueryRow(ctx, countOpenClosingPullRequests, issueID)
	var i CountOpenClosingPullRequestsRow
	err := row.Scan(&i.OpenCount, &i.MergedClosingCount)
	return i, err
}

const getActivePullRequest = `-- name: GetActivePullRequest :one
SELECT id, workspace_id, issue_id, repo_owner, repo_name, number, title, url, state, draft, head_branch, base_branch, author, source, close_intent, suppressed_at, merged_at, github_updated_at, created_at, updated_at FROM pull_requests
WHERE issue_id = $1
  AND state = 'open'
  AND close_intent
  AND suppressed_at IS NULL
ORDER BY created_at DESC
LIMIT 1
`

// The issue's live line of work: open, claiming to close the issue, and not
// unlinked by a human.
//
// It is also what a new task continues, which is why it is only reachable from
// the two certain entries: the platform opens a PR for a task, or a human links
// one. Nothing infers a link, so every row here is a statement rather than a
// guess. An inferred entry would have to be kept out of this query.
func (q *Queries) GetActivePullRequest(ctx context.Context, issueID uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getActivePullRequest, issueID)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Url,
		&i.State,
		&i.Draft,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Author,
		&i.Source,
		&i.CloseIntent,
		&i.SuppressedAt,
		&i.MergedAt,
		&i.GithubUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT id, workspace_id, issue_id, repo_owner, repo_name, number, title, url, state, draft, head_branch, base_branch, author, source, close_intent, suppressed_at, merged_at, github_updated_at, created_at, updated_at FROM pull_requests WHERE id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, id uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Url,
		&i.State,
		&i.Draft,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Author,
		&i.Source,
		&i.CloseIntent,
		&i.SuppressedAt,
		&i.MergedAt,
		&i.GithubUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPullRequestByNumber = `-- name: GetPullRequestByNumber :one
SELECT id, workspace_id, issue_id, repo_owner, repo_name, number, title, url, state, draft, head_branch, base_branch, author, source, close_intent, suppressed_at, merged_at, github_updated_at, created_at, updated_at FROM pull_requests
WHERE workspace_id = $1 AND repo_owner = $2 AND repo_name = $3 AND number = $4
`

type GetPullRequestByNumberParams struct {
	WorkspaceID uuid.UUID `json:"workspace_id"`
	RepoOwner   string    `json:"repo_owner"`
	RepoName    string    `json:"repo_name"`
	Number      int32     `json:"number"`
}

func (q *Queries) GetPullRequestByNumber(ctx context.Context, arg GetPullRequestByNumberParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequestByNumber,
		arg.WorkspaceID,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Url,
		&i.State,
		&i.Draft,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Author,
		&i.Source,
		&i.CloseIntent,
		&i.SuppressedAt,
		&i.MergedAt,
		&i.GithubUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertPullRequest = `-- name: InsertPullRequest :one
INSERT INTO pull_requests (
    workspace_id, issue_id, repo_owner, repo_name, number, title, url,
    state, draft, head_branch, base_branch, author, source, close_intent,
    merged_at, github_updated_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16
)
ON CONFLICT (workspace_id, repo_owner, repo_name, number) DO UPDATE SET
    title = EXCLUDED.title,
    url = EXCLUDED.url,
    state = EXCLUDED.state,
    draft = EXCLUDED.draft,
    head_branch = EXCLUDED.head_branch,
    base_branch = EXCLUDED.base_branch,
    author = EXCLUDED.author,
    close_intent = EXCLUDED.close_intent,
    merged_at = EXCLUDED.merged_at,
    github_updated_at = EXCLUDED.github_updated_at,
    updated_at = now()
RETURNING id, workspace_id, issue_id, repo_owner, repo_name, number, title, url, state, draft, head_branch, base_branch, author, source, close_intent, suppressed_at, merged_at, github_updated_at, created_at, updated_at
`

type InsertPullRequestParams struct {
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	IssueID         uuid.UUID  `json:"issue_id"`
	RepoOwner       string     `json:"repo_owner"`
	RepoName        string     `json:"repo_name"`
	Number          int32      `json:"number"`
	Title           string     `json:"title"`
	Url             string     `json:"url"`
	State           string     `json:"state"`
	Draft           bool       `json:"draft"`
	HeadBranch      string     `json:"head_branch"`
	BaseBranch      string     `json:"base_branch"`
	Author          string     `json:"author"`
	Source          string     `json:"source"`
	CloseIntent     bool       `json:"close_intent"`
	MergedAt        *time.Time `json:"merged_at"`
	GithubUpdatedAt *time.Time `json:"github_updated_at"`
}

// Writes a PR row, or refreshes it when the same PR is seen again. The caller
// (store.RecordPullRequest) only reaches this after a guarded update found
// nothing to do, so the values here are the newest we have seen.
func (q *Queries) InsertPullRequest(ctx context.Context, arg InsertPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, insertPullRequest,
		arg.WorkspaceID,
		arg.IssueID,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.Title,
		arg.Url,
		arg.State,
		arg.Draft,
		arg.HeadBranch,
		arg.BaseBranch,
		arg.Author,
		arg.Source,
		arg.CloseIntent,
		arg.MergedAt,
		arg.GithubUpdatedAt,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Url,
		&i.State,
		&i.Draft,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Author,
		&i.Source,
		&i.CloseIntent,
		&i.SuppressedAt,
		&i.MergedAt,
		&i.GithubUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPullRequestsByIssue = `-- name: ListPullRequestsByIssue :many
SELECT id, workspace_id, issue_id, repo_owner, repo_name, number, title, url, state, draft, head_branch, base_branch, author, source, close_intent, suppressed_at, merged_at, github_updated_at, created_at, updated_at FROM pull_requests
WHERE issue_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListPullRequestsByIssue(ctx context.Context, issueID uuid.UUID) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, listPullRequestsByIssue, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IssueID,
			&i.RepoOwner,
			&i.RepoName,
			&i.Number,
			&i.Title,
			&i.Url,
			&i.State,
			&i.Draft,
			&i.HeadBranch,
			&i.BaseBranch,
			&i.Author,
			&i.Source,
			&i.CloseIntent,
			&i.SuppressedAt,
			&i.MergedAt,
			&i.GithubUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const suppressPullRequest = `-- name: SuppressPullRequest :exec
UPDATE pull_requests
SET suppressed_at = now(), updated_at = now()
WHERE id = $1
`

// An unlink is a tombstone, not a delete: the row keeps the history and stops
// occupying the active slot, and the automatic entries know not to link it back.
func (q *Queries) SuppressPullRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, suppressPullRequest, id)
	return err
}

const touchPullRequest = `-- name: TouchPullRequest :one
UPDATE pull_requests SET
    title = $5,
    url = $6,
    state = $7,
    draft = $8,
    head_branch = $9,
    base_branch = $10,
    author = $11,
    close_intent = $12,
    merged_at = $13,
    github_updated_at = $14,
    updated_at = now()
WHERE workspace_id = $1 AND repo_owner = $2 AND repo_name = $3 AND number = $4
  AND (github_updated_at IS NULL OR $14::timestamptz IS NULL OR $14::timestamptz >= github_updated_at)
RETURNING id, workspace_id, issue_id, repo_owner, repo_name, number, title, url, state, draft, head_branch, base_branch, author, source, close_intent, suppressed_at, merged_at, github_updated_at, created_at, updated_at
`

type TouchPullRequestParams struct {
	WorkspaceID     uuid.UUID  `json:"workspace_id"`
	RepoOwner       string     `json:"repo_owner"`
	RepoName        string     `json:"repo_name"`
	Number          int32      `json:"number"`
	Title           string     `json:"title"`
	Url             string     `json:"url"`
	State           string     `json:"state"`
	Draft           bool       `json:"draft"`
	HeadBranch      string     `json:"head_branch"`
	BaseBranch      string     `json:"base_branch"`
	Author          string     `json:"author"`
	CloseIntent     bool       `json:"close_intent"`
	MergedAt        *time.Time `json:"merged_at"`
	GithubUpdatedAt *time.Time `json:"github_updated_at"`
}

// Refreshes an existing row from an event, but only when that event is at least
// as new as what is stored: GitHub does not guarantee delivery order, so a
// `merged` notification can arrive before the `opened` one it belongs to, and
// an older event must not roll the state back.
//
// Deliberately not `ON CONFLICT ... DO UPDATE ... WHERE`: Postgres returns no
// row from a WHERE'd conflict update, which would leave the caller unable to
// tell "nothing stored yet" from "stale event". Returning no rows here is
// unambiguous — the caller then looks the row up, or inserts it.
//
// issue_id, source, suppressed_at and created_at are never updated: a PR cannot
// move between issues, the first link is the provenance, and a human's unlink
// is only ever cleared by the unlink API.
func (q *Queries) TouchPullRequest(ctx context.Context, arg TouchPullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, touchPullRequest,
		arg.WorkspaceID,
		arg.RepoOwner,
		arg.RepoName,
		arg.Number,
		arg.Title,
		arg.Url,
		arg.State,
		arg.Draft,
		arg.HeadBranch,
		arg.BaseBranch,
		arg.Author,
		arg.CloseIntent,
		arg.MergedAt,
		arg.GithubUpdatedAt,
	)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.RepoOwner,
		&i.RepoName,
		&i.Number,
		&i.Title,
		&i.Url,
		&i.State,
		&i.Draft,
		&i.HeadBranch,
		&i.BaseBranch,
		&i.Author,
		&i.Source,
		&i.CloseIntent,
		&i.SuppressedAt,
		&i.MergedAt,
		&i.GithubUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unsuppressPullRequest = `-- name: UnsuppressPullRequest :exec
UPDATE pull_requests
SET suppressed_at = NULL, updated_at = now()
WHERE id = $1
`

// Re-linking needs the active slot back. The partial unique index refuses when
// another PR holds it, which is the rule: deal with the occupant first.
func (q *Queries) UnsuppressPullRequest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unsuppressPullRequest, id)
	return err
}
