// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: skills.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createSkill = `-- name: CreateSkill :one
INSERT INTO skills (workspace_id, name, description, content, created_by)
VALUES ($1, $2, $3, $4, $5) RETURNING id, workspace_id, name, description, content, created_by, created_at, updated_at
`

type CreateSkillParams struct {
	WorkspaceID uuid.UUID  `json:"workspace_id"`
	Name        string     `json:"name"`
	Description string     `json:"description"`
	Content     string     `json:"content"`
	CreatedBy   *uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateSkill(ctx context.Context, arg CreateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, createSkill,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Content,
		arg.CreatedBy,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAgentSkills = `-- name: DeleteAgentSkills :exec
DELETE FROM agent_skills WHERE agent_id = $1
`

func (q *Queries) DeleteAgentSkills(ctx context.Context, agentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentSkills, agentID)
	return err
}

const deleteSkill = `-- name: DeleteSkill :exec
DELETE FROM skills WHERE id = $1 AND workspace_id = $2
`

type DeleteSkillParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) DeleteSkill(ctx context.Context, arg DeleteSkillParams) error {
	_, err := q.db.Exec(ctx, deleteSkill, arg.ID, arg.WorkspaceID)
	return err
}

const getSkill = `-- name: GetSkill :one
SELECT id, workspace_id, name, description, content, created_by, created_at, updated_at FROM skills WHERE id = $1 AND workspace_id = $2
`

type GetSkillParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
}

func (q *Queries) GetSkill(ctx context.Context, arg GetSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, getSkill, arg.ID, arg.WorkspaceID)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertAgentSkill = `-- name: InsertAgentSkill :exec
INSERT INTO agent_skills (agent_id, skill_id) VALUES ($1, $2)
`

type InsertAgentSkillParams struct {
	AgentID uuid.UUID `json:"agent_id"`
	SkillID uuid.UUID `json:"skill_id"`
}

func (q *Queries) InsertAgentSkill(ctx context.Context, arg InsertAgentSkillParams) error {
	_, err := q.db.Exec(ctx, insertAgentSkill, arg.AgentID, arg.SkillID)
	return err
}

const listSkillsByWorkspace = `-- name: ListSkillsByWorkspace :many
SELECT id, workspace_id, name, description, content, created_by, created_at, updated_at FROM skills WHERE workspace_id = $1 ORDER BY name
`

func (q *Queries) ListSkillsByWorkspace(ctx context.Context, workspaceID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSkillsForAgent = `-- name: ListSkillsForAgent :many
SELECT s.id, s.workspace_id, s.name, s.description, s.content, s.created_by, s.created_at, s.updated_at FROM skills s
JOIN agent_skills ag ON ag.skill_id = s.id
WHERE ag.agent_id = $1 ORDER BY s.name
`

func (q *Queries) ListSkillsForAgent(ctx context.Context, agentID uuid.UUID) ([]Skill, error) {
	rows, err := q.db.Query(ctx, listSkillsForAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Skill
	for rows.Next() {
		var i Skill
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.Name,
			&i.Description,
			&i.Content,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSkill = `-- name: UpdateSkill :one
UPDATE skills SET name = $3, description = $4, content = $5, updated_at = now()
WHERE id = $1 AND workspace_id = $2 RETURNING id, workspace_id, name, description, content, created_by, created_at, updated_at
`

type UpdateSkillParams struct {
	ID          uuid.UUID `json:"id"`
	WorkspaceID uuid.UUID `json:"workspace_id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	Content     string    `json:"content"`
}

func (q *Queries) UpdateSkill(ctx context.Context, arg UpdateSkillParams) (Skill, error) {
	row := q.db.QueryRow(ctx, updateSkill,
		arg.ID,
		arg.WorkspaceID,
		arg.Name,
		arg.Description,
		arg.Content,
	)
	var i Skill
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.Name,
		&i.Description,
		&i.Content,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
