// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_usage.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listUsageByAgent = `-- name: ListUsageByAgent :many
SELECT a.id AS agent_id, a.name AS agent_name, a.avatar_url AS agent_avatar_url,
       sum(u.input_tokens)::bigint       AS input_tokens,
       sum(u.output_tokens)::bigint      AS output_tokens,
       sum(u.cache_read_tokens)::bigint  AS cache_read_tokens,
       sum(u.cache_write_tokens)::bigint AS cache_write_tokens,
       count(DISTINCT u.task_id)::int    AS run_count
FROM task_usage u
JOIN tasks t ON t.id = u.task_id
JOIN workspaces w ON w.id = t.workspace_id
JOIN agents a ON a.id = t.agent_id
WHERE w.user_id = $1
  AND u.created_at >= $2 AND u.created_at < $3
  AND t.workspace_id = coalesce($4::uuid, t.workspace_id)
GROUP BY a.id, a.name, a.avatar_url
ORDER BY sum(u.input_tokens + u.output_tokens + u.cache_read_tokens + u.cache_write_tokens) DESC
`

type ListUsageByAgentParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type ListUsageByAgentRow struct {
	AgentID          uuid.UUID `json:"agent_id"`
	AgentName        string    `json:"agent_name"`
	AgentAvatarUrl   string    `json:"agent_avatar_url"`
	InputTokens      int64     `json:"input_tokens"`
	OutputTokens     int64     `json:"output_tokens"`
	CacheReadTokens  int64     `json:"cache_read_tokens"`
	CacheWriteTokens int64     `json:"cache_write_tokens"`
	RunCount         int32     `json:"run_count"`
}

func (q *Queries) ListUsageByAgent(ctx context.Context, arg ListUsageByAgentParams) ([]ListUsageByAgentRow, error) {
	rows, err := q.db.Query(ctx, listUsageByAgent,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByAgentRow
	for rows.Next() {
		var i ListUsageByAgentRow
		if err := rows.Scan(
			&i.AgentID,
			&i.AgentName,
			&i.AgentAvatarUrl,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByDaemon = `-- name: ListUsageByDaemon :many
SELECT t.assigned_daemon_id AS daemon_id, coalesce(d.name, 'unassigned') AS daemon_name,
       sum(u.input_tokens)::bigint       AS input_tokens,
       sum(u.output_tokens)::bigint      AS output_tokens,
       sum(u.cache_read_tokens)::bigint  AS cache_read_tokens,
       sum(u.cache_write_tokens)::bigint AS cache_write_tokens,
       count(DISTINCT u.task_id)::int    AS run_count
FROM task_usage u
JOIN tasks t ON t.id = u.task_id
JOIN workspaces w ON w.id = t.workspace_id
LEFT JOIN daemons d ON d.id = t.assigned_daemon_id
WHERE w.user_id = $1
  AND u.created_at >= $2 AND u.created_at < $3
  AND t.workspace_id = coalesce($4::uuid, t.workspace_id)
GROUP BY t.assigned_daemon_id, d.name
ORDER BY sum(u.input_tokens + u.output_tokens + u.cache_read_tokens + u.cache_write_tokens) DESC
`

type ListUsageByDaemonParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type ListUsageByDaemonRow struct {
	DaemonID         *uuid.UUID `json:"daemon_id"`
	DaemonName       string     `json:"daemon_name"`
	InputTokens      int64      `json:"input_tokens"`
	OutputTokens     int64      `json:"output_tokens"`
	CacheReadTokens  int64      `json:"cache_read_tokens"`
	CacheWriteTokens int64      `json:"cache_write_tokens"`
	RunCount         int32      `json:"run_count"`
}

// The machine a run was dispatched to. assigned_daemon_id is nullable, so a run
// with no daemon is grouped under a NULL id and labelled rather than dropped —
// dropping it would make the rows stop adding up to the total beside them.
func (q *Queries) ListUsageByDaemon(ctx context.Context, arg ListUsageByDaemonParams) ([]ListUsageByDaemonRow, error) {
	rows, err := q.db.Query(ctx, listUsageByDaemon,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByDaemonRow
	for rows.Next() {
		var i ListUsageByDaemonRow
		if err := rows.Scan(
			&i.DaemonID,
			&i.DaemonName,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByIssue = `-- name: ListUsageByIssue :many
SELECT t.issue_id AS issue_id, i.number AS issue_number, i.title AS issue_title,
       w.issue_prefix AS issue_prefix, w.name AS workspace_name, w.slug AS workspace_slug,
       sum(u.input_tokens)::bigint       AS input_tokens,
       sum(u.output_tokens)::bigint      AS output_tokens,
       sum(u.cache_read_tokens)::bigint  AS cache_read_tokens,
       sum(u.cache_write_tokens)::bigint AS cache_write_tokens,
       count(DISTINCT u.task_id)::int    AS run_count
FROM task_usage u
JOIN tasks t ON t.id = u.task_id
JOIN workspaces w ON w.id = t.workspace_id
JOIN issues i ON i.id = t.issue_id
WHERE w.user_id = $1
  AND u.created_at >= $2 AND u.created_at < $3
  AND t.workspace_id = coalesce($4::uuid, t.workspace_id)
GROUP BY t.issue_id, i.number, i.title, w.issue_prefix, w.name, w.slug
ORDER BY sum(u.input_tokens + u.output_tokens + u.cache_read_tokens + u.cache_write_tokens) DESC
`

type ListUsageByIssueParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type ListUsageByIssueRow struct {
	IssueID          uuid.UUID `json:"issue_id"`
	IssueNumber      int32     `json:"issue_number"`
	IssueTitle       string    `json:"issue_title"`
	IssuePrefix      string    `json:"issue_prefix"`
	WorkspaceName    string    `json:"workspace_name"`
	WorkspaceSlug    string    `json:"workspace_slug"`
	InputTokens      int64     `json:"input_tokens"`
	OutputTokens     int64     `json:"output_tokens"`
	CacheReadTokens  int64     `json:"cache_read_tokens"`
	CacheWriteTokens int64     `json:"cache_write_tokens"`
	RunCount         int32     `json:"run_count"`
}

// issue_key is composed in Go from prefix + number, the same way the task
// payload and the agent list build it.
func (q *Queries) ListUsageByIssue(ctx context.Context, arg ListUsageByIssueParams) ([]ListUsageByIssueRow, error) {
	rows, err := q.db.Query(ctx, listUsageByIssue,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByIssueRow
	for rows.Next() {
		var i ListUsageByIssueRow
		if err := rows.Scan(
			&i.IssueID,
			&i.IssueNumber,
			&i.IssueTitle,
			&i.IssuePrefix,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByModel = `-- name: ListUsageByModel :many
SELECT u.provider, u.model,
       sum(u.input_tokens)::bigint       AS input_tokens,
       sum(u.output_tokens)::bigint      AS output_tokens,
       sum(u.cache_read_tokens)::bigint  AS cache_read_tokens,
       sum(u.cache_write_tokens)::bigint AS cache_write_tokens,
       count(DISTINCT u.task_id)::int    AS run_count
FROM task_usage u
JOIN tasks t ON t.id = u.task_id
JOIN workspaces w ON w.id = t.workspace_id
WHERE w.user_id = $1
  AND u.created_at >= $2 AND u.created_at < $3
  AND t.workspace_id = coalesce($4::uuid, t.workspace_id)
GROUP BY u.provider, u.model
ORDER BY sum(u.input_tokens + u.output_tokens + u.cache_read_tokens + u.cache_write_tokens) DESC
`

type ListUsageByModelParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type ListUsageByModelRow struct {
	Provider         string `json:"provider"`
	Model            string `json:"model"`
	InputTokens      int64  `json:"input_tokens"`
	OutputTokens     int64  `json:"output_tokens"`
	CacheReadTokens  int64  `json:"cache_read_tokens"`
	CacheWriteTokens int64  `json:"cache_write_tokens"`
	RunCount         int32  `json:"run_count"`
}

// Grouped by provider *and* model: the same model id can be served by different
// providers, and their tokens are not comparable.
func (q *Queries) ListUsageByModel(ctx context.Context, arg ListUsageByModelParams) ([]ListUsageByModelRow, error) {
	rows, err := q.db.Query(ctx, listUsageByModel,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByModelRow
	for rows.Next() {
		var i ListUsageByModelRow
		if err := rows.Scan(
			&i.Provider,
			&i.Model,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageByWorkspace = `-- name: ListUsageByWorkspace :many
SELECT w.id AS workspace_id, w.name AS workspace_name, w.slug AS workspace_slug,
       sum(u.input_tokens)::bigint       AS input_tokens,
       sum(u.output_tokens)::bigint      AS output_tokens,
       sum(u.cache_read_tokens)::bigint  AS cache_read_tokens,
       sum(u.cache_write_tokens)::bigint AS cache_write_tokens,
       count(DISTINCT u.task_id)::int    AS run_count
FROM task_usage u
JOIN tasks t ON t.id = u.task_id
JOIN workspaces w ON w.id = t.workspace_id
WHERE w.user_id = $1
  AND u.created_at >= $2 AND u.created_at < $3
GROUP BY w.id, w.name, w.slug
ORDER BY sum(u.input_tokens + u.output_tokens + u.cache_read_tokens + u.cache_write_tokens) DESC
`

type ListUsageByWorkspaceParams struct {
	UserID uuid.UUID `json:"user_id"`
	FromAt time.Time `json:"from_at"`
	ToAt   time.Time `json:"to_at"`
}

type ListUsageByWorkspaceRow struct {
	WorkspaceID      uuid.UUID `json:"workspace_id"`
	WorkspaceName    string    `json:"workspace_name"`
	WorkspaceSlug    string    `json:"workspace_slug"`
	InputTokens      int64     `json:"input_tokens"`
	OutputTokens     int64     `json:"output_tokens"`
	CacheReadTokens  int64     `json:"cache_read_tokens"`
	CacheWriteTokens int64     `json:"cache_write_tokens"`
	RunCount         int32     `json:"run_count"`
}

func (q *Queries) ListUsageByWorkspace(ctx context.Context, arg ListUsageByWorkspaceParams) ([]ListUsageByWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listUsageByWorkspace, arg.UserID, arg.FromAt, arg.ToAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageByWorkspaceRow
	for rows.Next() {
		var i ListUsageByWorkspaceRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.WorkspaceName,
			&i.WorkspaceSlug,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsageSeries = `-- name: ListUsageSeries :many
SELECT bucket,
       sum(input_tokens)::bigint       AS input_tokens,
       sum(output_tokens)::bigint      AS output_tokens,
       sum(cache_read_tokens)::bigint  AS cache_read_tokens,
       sum(cache_write_tokens)::bigint AS cache_write_tokens,
       count(DISTINCT task_id)::int    AS run_count
FROM (
    SELECT (CASE WHEN $1::text = 'hour'
                 THEN to_char(date_trunc('hour', u.created_at AT TIME ZONE $2::text), 'YYYY-MM-DD"T"HH24:00')
                 ELSE to_char(date_trunc('day', u.created_at AT TIME ZONE $2::text), 'YYYY-MM-DD')
            END)::text AS bucket,
           u.task_id, u.input_tokens, u.output_tokens, u.cache_read_tokens, u.cache_write_tokens
    FROM task_usage u
    JOIN tasks t ON t.id = u.task_id
    JOIN workspaces w ON w.id = t.workspace_id
    WHERE w.user_id = $3
      AND u.created_at >= $4 AND u.created_at < $5
      AND t.workspace_id = coalesce($6::uuid, t.workspace_id)
) b
GROUP BY bucket
ORDER BY bucket
`

type ListUsageSeriesParams struct {
	Bucket      string     `json:"bucket"`
	Tz          string     `json:"tz"`
	UserID      uuid.UUID  `json:"user_id"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type ListUsageSeriesRow struct {
	Bucket           string `json:"bucket"`
	InputTokens      int64  `json:"input_tokens"`
	OutputTokens     int64  `json:"output_tokens"`
	CacheReadTokens  int64  `json:"cache_read_tokens"`
	CacheWriteTokens int64  `json:"cache_write_tokens"`
	RunCount         int32  `json:"run_count"`
}

// The trend chart. Buckets are cut in the viewer's timezone via the tz argument
// rather than fixed in UTC, so "yesterday" means yesterday where the reader is;
// rolling windows then land on local day boundaries instead of drifting.
// The bucket is formatted as text so no timezone can be reintroduced on scan.
func (q *Queries) ListUsageSeries(ctx context.Context, arg ListUsageSeriesParams) ([]ListUsageSeriesRow, error) {
	rows, err := q.db.Query(ctx, listUsageSeries,
		arg.Bucket,
		arg.Tz,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.WorkspaceID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsageSeriesRow
	for rows.Next() {
		var i ListUsageSeriesRow
		if err := rows.Scan(
			&i.Bucket,
			&i.InputTokens,
			&i.OutputTokens,
			&i.CacheReadTokens,
			&i.CacheWriteTokens,
			&i.RunCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const summarizeUsage = `-- name: SummarizeUsage :one
SELECT
    coalesce(sum(u.input_tokens), 0)::bigint       AS input_tokens,
    coalesce(sum(u.output_tokens), 0)::bigint      AS output_tokens,
    coalesce(sum(u.cache_read_tokens), 0)::bigint  AS cache_read_tokens,
    coalesce(sum(u.cache_write_tokens), 0)::bigint AS cache_write_tokens,
    count(DISTINCT u.task_id)::int                 AS runs_with_usage,
    (SELECT count(*)::int FROM tasks t2
     JOIN workspaces w2 ON w2.id = t2.workspace_id
     WHERE w2.user_id = $1
       AND t2.completed_at >= $2::timestamptz AND t2.completed_at < $3::timestamptz
       AND t2.workspace_id = coalesce($4::uuid, t2.workspace_id)
    )::int AS runs_total
FROM task_usage u
JOIN tasks t ON t.id = u.task_id
JOIN workspaces w ON w.id = t.workspace_id
WHERE w.user_id = $1
  AND u.created_at >= $2 AND u.created_at < $3
  AND t.workspace_id = coalesce($4::uuid, t.workspace_id)
`

type SummarizeUsageParams struct {
	UserID      uuid.UUID  `json:"user_id"`
	FromAt      time.Time  `json:"from_at"`
	ToAt        time.Time  `json:"to_at"`
	WorkspaceID *uuid.UUID `json:"workspace_id"`
}

type SummarizeUsageRow struct {
	InputTokens      int64 `json:"input_tokens"`
	OutputTokens     int64 `json:"output_tokens"`
	CacheReadTokens  int64 `json:"cache_read_tokens"`
	CacheWriteTokens int64 `json:"cache_write_tokens"`
	RunsWithUsage    int32 `json:"runs_with_usage"`
	RunsTotal        int32 `json:"runs_total"`
}

// Totals for a window, plus the coverage that keeps the UI honest.
//
// runs_total counts runs that *finished* in the window (completed_at), because
// that is when usage is written. The gap between it and runs_with_usage is
// usage we never received — a daemon that died mid-task, a provider that does
// not report tokens, or a run from before this table existed. Those are not
// zero-token runs and must not be rendered as such.
func (q *Queries) SummarizeUsage(ctx context.Context, arg SummarizeUsageParams) (SummarizeUsageRow, error) {
	row := q.db.QueryRow(ctx, summarizeUsage,
		arg.UserID,
		arg.FromAt,
		arg.ToAt,
		arg.WorkspaceID,
	)
	var i SummarizeUsageRow
	err := row.Scan(
		&i.InputTokens,
		&i.OutputTokens,
		&i.CacheReadTokens,
		&i.CacheWriteTokens,
		&i.RunsWithUsage,
		&i.RunsTotal,
	)
	return i, err
}

const upsertTaskUsage = `-- name: UpsertTaskUsage :exec

INSERT INTO task_usage (task_id, provider, model, input_tokens, output_tokens, cache_read_tokens, cache_write_tokens, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, now())
ON CONFLICT (task_id, provider, model) DO UPDATE SET
    -- Overwrite rather than add: a replayed report is a correction, not more
    -- usage. The daemon is the source of truth for its own run.
    input_tokens = EXCLUDED.input_tokens,
    output_tokens = EXCLUDED.output_tokens,
    cache_read_tokens = EXCLUDED.cache_read_tokens,
    cache_write_tokens = EXCLUDED.cache_write_tokens,
    updated_at = now()
`

type UpsertTaskUsageParams struct {
	TaskID           uuid.UUID `json:"task_id"`
	Provider         string    `json:"provider"`
	Model            string    `json:"model"`
	InputTokens      int64     `json:"input_tokens"`
	OutputTokens     int64     `json:"output_tokens"`
	CacheReadTokens  int64     `json:"cache_read_tokens"`
	CacheWriteTokens int64     `json:"cache_write_tokens"`
}

// Reads of the token-usage ledger. Every query is scoped to the workspaces a
// user owns and to a half-open [from_at, to_at) window on the usage row, which
// is written when the run finishes.
func (q *Queries) UpsertTaskUsage(ctx context.Context, arg UpsertTaskUsageParams) error {
	_, err := q.db.Exec(ctx, upsertTaskUsage,
		arg.TaskID,
		arg.Provider,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.CacheReadTokens,
		arg.CacheWriteTokens,
	)
	return err
}
