// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const claimNextTask = `-- name: ClaimNextTask :one
UPDATE tasks
SET status = 'dispatched', dispatched_at = now(), updated_at = now()
WHERE tasks.id = (
    SELECT t.id FROM tasks t
    WHERE t.assigned_daemon_id = $1 AND t.status = 'queued'
    ORDER BY t.priority DESC, t.created_at ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) ClaimNextTask(ctx context.Context, assignedDaemonID *uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, claimNextTask, assignedDaemonID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (workspace_id, issue_id, agent_id, assigned_daemon_id, provider, model, context)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

type CreateTaskParams struct {
	WorkspaceID      uuid.UUID  `json:"workspace_id"`
	IssueID          uuid.UUID  `json:"issue_id"`
	AgentID          uuid.UUID  `json:"agent_id"`
	AssignedDaemonID *uuid.UUID `json:"assigned_daemon_id"`
	Provider         string     `json:"provider"`
	Model            string     `json:"model"`
	Context          []byte     `json:"context"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.WorkspaceID,
		arg.IssueID,
		arg.AgentID,
		arg.AssignedDaemonID,
		arg.Provider,
		arg.Model,
		arg.Context,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const failTasksOfSilentDaemons = `-- name: FailTasksOfSilentDaemons :many
UPDATE tasks
SET status = 'failed', failure_reason = 'runtime_offline', completed_at = now(), updated_at = now()
WHERE status IN ('dispatched','running')
  AND assigned_daemon_id IS NOT NULL
  AND assigned_daemon_id IN (
      SELECT id FROM daemons
      WHERE COALESCE(last_seen_at, registered_at) < now() - make_interval(secs => $1::double precision)
  )
RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

// Fails the in-flight tasks of every daemon that has stopped heartbeating for at
// least @grace_seconds, returning them so the caller can tell their issues.
//
// Why the delay is measured from the heartbeat and not from the socket: a socket
// ending says nothing about whether its daemon can still finish and report the
// task. A NAT rebind, a suspended laptop or a server-side read deadline all end
// the socket while the daemon keeps working, and task results travel over HTTP,
// not the WebSocket. The only honest evidence of absence is the signal the
// daemon repeats on its own schedule — so a task lives exactly as long as its
// daemon keeps checking in, and this grace is that same clock.
//
// COALESCE mirrors the staleness rule used elsewhere: a daemon that never
// connected has no last_seen_at, so its registration time stands in.
func (q *Queries) FailTasksOfSilentDaemons(ctx context.Context, graceSeconds float64) ([]Task, error) {
	rows, err := q.db.Query(ctx, failTasksOfSilentDaemons, graceSeconds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.IssueID,
			&i.AgentID,
			&i.Status,
			&i.AssignedDaemonID,
			&i.Provider,
			&i.Model,
			&i.Priority,
			&i.Context,
			&i.Result,
			&i.Error,
			&i.FailureReason,
			&i.DispatchedAt,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTask = `-- name: GetTask :one
SELECT id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at FROM tasks WHERE id = $1
`

func (q *Queries) GetTask(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const hasPendingForDaemon = `-- name: HasPendingForDaemon :one
SELECT EXISTS(SELECT 1 FROM tasks WHERE assigned_daemon_id = $1 AND status = 'queued') AS has_pending
`

func (q *Queries) HasPendingForDaemon(ctx context.Context, assignedDaemonID *uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, hasPendingForDaemon, assignedDaemonID)
	var has_pending bool
	err := row.Scan(&has_pending)
	return has_pending, err
}

const insertTaskMessage = `-- name: InsertTaskMessage :one
INSERT INTO task_messages (task_id, seq, type, tool, content, input, output)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, task_id, seq, type, tool, content, input, output, created_at
`

type InsertTaskMessageParams struct {
	TaskID  uuid.UUID `json:"task_id"`
	Seq     int32     `json:"seq"`
	Type    string    `json:"type"`
	Tool    *string   `json:"tool"`
	Content *string   `json:"content"`
	Input   []byte    `json:"input"`
	Output  *string   `json:"output"`
}

func (q *Queries) InsertTaskMessage(ctx context.Context, arg InsertTaskMessageParams) (TaskMessage, error) {
	row := q.db.QueryRow(ctx, insertTaskMessage,
		arg.TaskID,
		arg.Seq,
		arg.Type,
		arg.Tool,
		arg.Content,
		arg.Input,
		arg.Output,
	)
	var i TaskMessage
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.Seq,
		&i.Type,
		&i.Tool,
		&i.Content,
		&i.Input,
		&i.Output,
		&i.CreatedAt,
	)
	return i, err
}

const listTaskMessages = `-- name: ListTaskMessages :many
SELECT id, task_id, seq, type, tool, content, input, output, created_at FROM task_messages WHERE task_id = $1 AND seq > $2 ORDER BY seq ASC
`

type ListTaskMessagesParams struct {
	TaskID uuid.UUID `json:"task_id"`
	Seq    int32     `json:"seq"`
}

func (q *Queries) ListTaskMessages(ctx context.Context, arg ListTaskMessagesParams) ([]TaskMessage, error) {
	rows, err := q.db.Query(ctx, listTaskMessages, arg.TaskID, arg.Seq)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaskMessage
	for rows.Next() {
		var i TaskMessage
		if err := rows.Scan(
			&i.ID,
			&i.TaskID,
			&i.Seq,
			&i.Type,
			&i.Tool,
			&i.Content,
			&i.Input,
			&i.Output,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTaskCompleted = `-- name: MarkTaskCompleted :one
UPDATE tasks SET status = 'completed', completed_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('dispatched','running') RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) MarkTaskCompleted(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskCompleted, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTaskFailed = `-- name: MarkTaskFailed :one
UPDATE tasks SET status = 'failed', error = $2, failure_reason = $3, completed_at = now(), updated_at = now()
WHERE id = $1 AND status IN ('dispatched','running') RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

type MarkTaskFailedParams struct {
	ID            uuid.UUID `json:"id"`
	Error         string    `json:"error"`
	FailureReason *string   `json:"failure_reason"`
}

func (q *Queries) MarkTaskFailed(ctx context.Context, arg MarkTaskFailedParams) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskFailed, arg.ID, arg.Error, arg.FailureReason)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const markTaskRunning = `-- name: MarkTaskRunning :one
UPDATE tasks SET status = 'running', started_at = now(), updated_at = now()
WHERE id = $1 AND status = 'dispatched' RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) MarkTaskRunning(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, markTaskRunning, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextTaskMessageSeq = `-- name: NextTaskMessageSeq :one
SELECT COALESCE(MAX(seq), 0)::int AS seq FROM task_messages WHERE task_id = $1
`

func (q *Queries) NextTaskMessageSeq(ctx context.Context, taskID uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, nextTaskMessageSeq, taskID)
	var seq int32
	err := row.Scan(&seq)
	return seq, err
}

const revertTaskToQueued = `-- name: RevertTaskToQueued :one
UPDATE tasks SET status = 'queued', dispatched_at = NULL, updated_at = now()
WHERE id = $1 AND status = 'dispatched' RETURNING id, workspace_id, issue_id, agent_id, status, assigned_daemon_id, provider, model, priority, context, result, error, failure_reason, dispatched_at, started_at, completed_at, created_at, updated_at
`

func (q *Queries) RevertTaskToQueued(ctx context.Context, id uuid.UUID) (Task, error) {
	row := q.db.QueryRow(ctx, revertTaskToQueued, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.IssueID,
		&i.AgentID,
		&i.Status,
		&i.AssignedDaemonID,
		&i.Provider,
		&i.Model,
		&i.Priority,
		&i.Context,
		&i.Result,
		&i.Error,
		&i.FailureReason,
		&i.DispatchedAt,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTaskResult = `-- name: SetTaskResult :exec
UPDATE tasks SET result = $2, updated_at = now() WHERE id = $1
`

type SetTaskResultParams struct {
	ID     uuid.UUID `json:"id"`
	Result []byte    `json:"result"`
}

func (q *Queries) SetTaskResult(ctx context.Context, arg SetTaskResultParams) error {
	_, err := q.db.Exec(ctx, setTaskResult, arg.ID, arg.Result)
	return err
}
