// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIdentity = `-- name: CreateIdentity :one
INSERT INTO user_identities (user_id, provider, provider_user_id, provider_login, email, access_token, refresh_token)
VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, user_id, provider, provider_user_id, provider_login, email, access_token, refresh_token, created_at, updated_at
`

type CreateIdentityParams struct {
	UserID         uuid.UUID `json:"user_id"`
	Provider       string    `json:"provider"`
	ProviderUserID string    `json:"provider_user_id"`
	ProviderLogin  string    `json:"provider_login"`
	Email          *string   `json:"email"`
	AccessToken    *string   `json:"access_token"`
	RefreshToken   *string   `json:"refresh_token"`
}

func (q *Queries) CreateIdentity(ctx context.Context, arg CreateIdentityParams) (UserIdentity, error) {
	row := q.db.QueryRow(ctx, createIdentity,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.ProviderLogin,
		arg.Email,
		arg.AccessToken,
		arg.RefreshToken,
	)
	var i UserIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderLogin,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (login, avatar_url) VALUES ($1, $2) RETURNING id, login, avatar_url, created_at, updated_at
`

type CreateUserParams struct {
	Login     string  `json:"login"`
	AvatarUrl *string `json:"avatar_url"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Login, arg.AvatarUrl)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findIdentityByProvider = `-- name: FindIdentityByProvider :one
SELECT ui.id, ui.user_id, ui.provider, ui.provider_user_id, ui.provider_login, ui.email, ui.access_token, ui.refresh_token, ui.created_at, ui.updated_at, u.id as user_id, u.login as user_login, u.avatar_url as user_avatar_url,
       u.created_at as user_created_at, u.updated_at as user_updated_at
FROM user_identities ui
JOIN users u ON u.id = ui.user_id
WHERE ui.provider = $1 AND ui.provider_user_id = $2
`

type FindIdentityByProviderParams struct {
	Provider       string `json:"provider"`
	ProviderUserID string `json:"provider_user_id"`
}

type FindIdentityByProviderRow struct {
	ID             uuid.UUID          `json:"id"`
	UserID         uuid.UUID          `json:"user_id"`
	Provider       string             `json:"provider"`
	ProviderUserID string             `json:"provider_user_id"`
	ProviderLogin  string             `json:"provider_login"`
	Email          *string            `json:"email"`
	AccessToken    *string            `json:"access_token"`
	RefreshToken   *string            `json:"refresh_token"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
	UserID_2       uuid.UUID          `json:"user_id_2"`
	UserLogin      string             `json:"user_login"`
	UserAvatarUrl  *string            `json:"user_avatar_url"`
	UserCreatedAt  pgtype.Timestamptz `json:"user_created_at"`
	UserUpdatedAt  pgtype.Timestamptz `json:"user_updated_at"`
}

func (q *Queries) FindIdentityByProvider(ctx context.Context, arg FindIdentityByProviderParams) (FindIdentityByProviderRow, error) {
	row := q.db.QueryRow(ctx, findIdentityByProvider, arg.Provider, arg.ProviderUserID)
	var i FindIdentityByProviderRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.ProviderLogin,
		&i.Email,
		&i.AccessToken,
		&i.RefreshToken,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID_2,
		&i.UserLogin,
		&i.UserAvatarUrl,
		&i.UserCreatedAt,
		&i.UserUpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, login, avatar_url, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Login,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIdentityTokens = `-- name: UpdateIdentityTokens :exec
UPDATE user_identities SET access_token = $2, refresh_token = $3, updated_at = now() WHERE id = $1
`

type UpdateIdentityTokensParams struct {
	ID           uuid.UUID `json:"id"`
	AccessToken  *string   `json:"access_token"`
	RefreshToken *string   `json:"refresh_token"`
}

func (q *Queries) UpdateIdentityTokens(ctx context.Context, arg UpdateIdentityTokensParams) error {
	_, err := q.db.Exec(ctx, updateIdentityTokens, arg.ID, arg.AccessToken, arg.RefreshToken)
	return err
}

const updateUserAvatar = `-- name: UpdateUserAvatar :exec
UPDATE users SET avatar_url = $2, updated_at = now() WHERE id = $1
`

type UpdateUserAvatarParams struct {
	ID        uuid.UUID `json:"id"`
	AvatarUrl *string   `json:"avatar_url"`
}

func (q *Queries) UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error {
	_, err := q.db.Exec(ctx, updateUserAvatar, arg.ID, arg.AvatarUrl)
	return err
}
