// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, installation_id, github_repo_id, name)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at
`

type CreateWorkspaceParams struct {
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.UserID,
		arg.InstallationID,
		arg.GithubRepoID,
		arg.Name,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceWithRepo = `-- name: GetWorkspaceWithRepo :one
SELECT w.id, w.user_id, w.installation_id, w.github_repo_id, w.name, w.status, w.created_at, w.updated_at,
       r.full_name AS repo_full_name, r.owner AS repo_owner, r.name AS repo_name, r.private AS repo_private
FROM workspaces w
JOIN github_repos r ON r.id = w.github_repo_id
WHERE w.id = $1
`

type GetWorkspaceWithRepoRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	RepoFullName   string    `json:"repo_full_name"`
	RepoOwner      string    `json:"repo_owner"`
	RepoName       string    `json:"repo_name"`
	RepoPrivate    bool      `json:"repo_private"`
}

func (q *Queries) GetWorkspaceWithRepo(ctx context.Context, id uuid.UUID) (GetWorkspaceWithRepoRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceWithRepo, id)
	var i GetWorkspaceWithRepoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RepoFullName,
		&i.RepoOwner,
		&i.RepoName,
		&i.RepoPrivate,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at FROM workspaces WHERE user_id = $1 AND status != 'archived' ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.GithubRepoID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithRepo = `-- name: ListWorkspacesWithRepo :many
SELECT w.id, w.user_id, w.installation_id, w.github_repo_id, w.name, w.status, w.created_at, w.updated_at,
       r.full_name AS repo_full_name, r.owner AS repo_owner, r.name AS repo_name, r.private AS repo_private
FROM workspaces w
JOIN github_repos r ON r.id = w.github_repo_id
WHERE w.user_id = $1 AND w.status != 'archived'
ORDER BY w.created_at DESC
`

type ListWorkspacesWithRepoRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	RepoFullName   string    `json:"repo_full_name"`
	RepoOwner      string    `json:"repo_owner"`
	RepoName       string    `json:"repo_name"`
	RepoPrivate    bool      `json:"repo_private"`
}

func (q *Queries) ListWorkspacesWithRepo(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesWithRepoRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithRepo, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesWithRepoRow
	for rows.Next() {
		var i ListWorkspacesWithRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.GithubRepoID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.RepoFullName,
			&i.RepoOwner,
			&i.RepoName,
			&i.RepoPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :exec
UPDATE workspaces SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateWorkspaceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceStatus, arg.ID, arg.Status)
	return err
}
