// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, installation_id, github_repo_id, name)
VALUES ($1, $2, $3, $4) RETURNING id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at
`

type CreateWorkspaceParams struct {
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.UserID,
		arg.InstallationID,
		arg.GithubRepoID,
		arg.Name,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at FROM workspaces WHERE user_id = $1 AND status != 'archived' ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.GithubRepoID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :exec
UPDATE workspaces SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateWorkspaceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceStatus, arg.ID, arg.Status)
	return err
}
