// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces (user_id, installation_id, github_repo_id, name, issue_prefix, slug)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at, issue_prefix, issue_counter, avatar_url, slug
`

type CreateWorkspaceParams struct {
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
	IssuePrefix    string    `json:"issue_prefix"`
	Slug           string    `json:"slug"`
}

func (q *Queries) CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace,
		arg.UserID,
		arg.InstallationID,
		arg.GithubRepoID,
		arg.Name,
		arg.IssuePrefix,
		arg.Slug,
	)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AvatarUrl,
		&i.Slug,
	)
	return i, err
}

const deleteWorkspace = `-- name: DeleteWorkspace :exec
DELETE FROM workspaces WHERE id = $1
`

func (q *Queries) DeleteWorkspace(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteWorkspace, id)
	return err
}

const getWorkspace = `-- name: GetWorkspace :one
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at, issue_prefix, issue_counter, avatar_url, slug FROM workspaces WHERE id = $1
`

func (q *Queries) GetWorkspace(ctx context.Context, id uuid.UUID) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspace, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AvatarUrl,
		&i.Slug,
	)
	return i, err
}

const getWorkspaceByRepo = `-- name: GetWorkspaceByRepo :one
SELECT w.id, w.user_id, w.installation_id, w.github_repo_id, w.name, w.status
FROM workspaces w
JOIN github_repos r ON r.id = w.github_repo_id
JOIN github_installations i ON i.id = w.installation_id
WHERE i.installation_id = $1 AND r.owner = $2 AND r.name = $3
  AND w.status != 'archived'
ORDER BY w.created_at ASC
LIMIT 1
`

type GetWorkspaceByRepoParams struct {
	InstallationID int64  `json:"installation_id"`
	Owner          string `json:"owner"`
	Name           string `json:"name"`
}

type GetWorkspaceByRepoRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
}

// Resolves the workspace a webhook's repository belongs to. Excludes archived
// workspaces: once a workspace is archived its repos stop driving issue state.
func (q *Queries) GetWorkspaceByRepo(ctx context.Context, arg GetWorkspaceByRepoParams) (GetWorkspaceByRepoRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByRepo, arg.InstallationID, arg.Owner, arg.Name)
	var i GetWorkspaceByRepoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
	)
	return i, err
}

const getWorkspaceBySlug = `-- name: GetWorkspaceBySlug :one
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at, issue_prefix, issue_counter, avatar_url, slug FROM workspaces WHERE user_id = $1 AND slug = $2 AND status != 'archived'
`

type GetWorkspaceBySlugParams struct {
	UserID uuid.UUID `json:"user_id"`
	Slug   string    `json:"slug"`
}

func (q *Queries) GetWorkspaceBySlug(ctx context.Context, arg GetWorkspaceBySlugParams) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceBySlug, arg.UserID, arg.Slug)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.IssuePrefix,
		&i.IssueCounter,
		&i.AvatarUrl,
		&i.Slug,
	)
	return i, err
}

const getWorkspaceWithRepo = `-- name: GetWorkspaceWithRepo :one
SELECT w.id, w.user_id, w.installation_id, w.github_repo_id, w.name, w.status, w.created_at, w.updated_at, w.slug,
       w.avatar_url,
       r.full_name AS repo_full_name, r.owner AS repo_owner, r.name AS repo_name, r.private AS repo_private,
       r.default_branch AS repo_default_branch
FROM workspaces w
JOIN github_repos r ON r.id = w.github_repo_id
WHERE w.id = $1
`

type GetWorkspaceWithRepoRow struct {
	ID                uuid.UUID `json:"id"`
	UserID            uuid.UUID `json:"user_id"`
	InstallationID    uuid.UUID `json:"installation_id"`
	GithubRepoID      uuid.UUID `json:"github_repo_id"`
	Name              string    `json:"name"`
	Status            string    `json:"status"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
	Slug              string    `json:"slug"`
	AvatarUrl         string    `json:"avatar_url"`
	RepoFullName      string    `json:"repo_full_name"`
	RepoOwner         string    `json:"repo_owner"`
	RepoName          string    `json:"repo_name"`
	RepoPrivate       bool      `json:"repo_private"`
	RepoDefaultBranch string    `json:"repo_default_branch"`
}

func (q *Queries) GetWorkspaceWithRepo(ctx context.Context, id uuid.UUID) (GetWorkspaceWithRepoRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceWithRepo, id)
	var i GetWorkspaceWithRepoRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InstallationID,
		&i.GithubRepoID,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.AvatarUrl,
		&i.RepoFullName,
		&i.RepoOwner,
		&i.RepoName,
		&i.RepoPrivate,
		&i.RepoDefaultBranch,
	)
	return i, err
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT u.id, u.login, COALESCE(u.avatar_url, '') AS avatar_url
FROM workspaces w
JOIN users u ON u.id = w.user_id
WHERE w.id = $1
ORDER BY u.login
`

type ListWorkspaceMembersRow struct {
	ID        uuid.UUID `json:"id"`
	Login     string    `json:"login"`
	AvatarUrl string    `json:"avatar_url"`
}

// The people an issue can be assigned to. Today a workspace has exactly one
// member — the user it belongs to — so this returns one row. It is an endpoint
// rather than a hardcoded "me" so that collaboration is a change here, not a
// change to every caller.
func (q *Queries) ListWorkspaceMembers(ctx context.Context, id uuid.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(&i.ID, &i.Login, &i.AvatarUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesByUser = `-- name: ListWorkspacesByUser :many
SELECT id, user_id, installation_id, github_repo_id, name, status, created_at, updated_at, issue_prefix, issue_counter, avatar_url, slug FROM workspaces WHERE user_id = $1 AND status != 'archived' ORDER BY created_at DESC
`

func (q *Queries) ListWorkspacesByUser(ctx context.Context, userID uuid.UUID) ([]Workspace, error) {
	rows, err := q.db.Query(ctx, listWorkspacesByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Workspace
	for rows.Next() {
		var i Workspace
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.GithubRepoID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.IssuePrefix,
			&i.IssueCounter,
			&i.AvatarUrl,
			&i.Slug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspacesWithRepo = `-- name: ListWorkspacesWithRepo :many
SELECT w.id, w.user_id, w.installation_id, w.github_repo_id, w.name, w.status, w.created_at, w.updated_at, w.slug,
       w.avatar_url,
       r.full_name AS repo_full_name, r.owner AS repo_owner, r.name AS repo_name, r.private AS repo_private
FROM workspaces w
JOIN github_repos r ON r.id = w.github_repo_id
WHERE w.user_id = $1 AND w.status != 'archived'
ORDER BY w.created_at DESC
`

type ListWorkspacesWithRepoRow struct {
	ID             uuid.UUID `json:"id"`
	UserID         uuid.UUID `json:"user_id"`
	InstallationID uuid.UUID `json:"installation_id"`
	GithubRepoID   uuid.UUID `json:"github_repo_id"`
	Name           string    `json:"name"`
	Status         string    `json:"status"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`
	Slug           string    `json:"slug"`
	AvatarUrl      string    `json:"avatar_url"`
	RepoFullName   string    `json:"repo_full_name"`
	RepoOwner      string    `json:"repo_owner"`
	RepoName       string    `json:"repo_name"`
	RepoPrivate    bool      `json:"repo_private"`
}

func (q *Queries) ListWorkspacesWithRepo(ctx context.Context, userID uuid.UUID) ([]ListWorkspacesWithRepoRow, error) {
	rows, err := q.db.Query(ctx, listWorkspacesWithRepo, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspacesWithRepoRow
	for rows.Next() {
		var i ListWorkspacesWithRepoRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.InstallationID,
			&i.GithubRepoID,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.AvatarUrl,
			&i.RepoFullName,
			&i.RepoOwner,
			&i.RepoName,
			&i.RepoPrivate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceAvatar = `-- name: UpdateWorkspaceAvatar :exec
UPDATE workspaces SET avatar_url = $2, updated_at = now() WHERE id = $1
`

type UpdateWorkspaceAvatarParams struct {
	ID        uuid.UUID `json:"id"`
	AvatarUrl string    `json:"avatar_url"`
}

func (q *Queries) UpdateWorkspaceAvatar(ctx context.Context, arg UpdateWorkspaceAvatarParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceAvatar, arg.ID, arg.AvatarUrl)
	return err
}

const updateWorkspaceStatus = `-- name: UpdateWorkspaceStatus :exec
UPDATE workspaces SET status = $2, updated_at = now() WHERE id = $1
`

type UpdateWorkspaceStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdateWorkspaceStatus(ctx context.Context, arg UpdateWorkspaceStatusParams) error {
	_, err := q.db.Exec(ctx, updateWorkspaceStatus, arg.ID, arg.Status)
	return err
}
